"""DOCX exporter — write a rendered python-docx Document to disk with metadata."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from docforge.logging.setup import get_logger

logger = get_logger(__name__)

try:
    from importlib.metadata import version as pkg_version

    _DOCFORGE_VERSION = pkg_version("docforge")
except Exception:
    _DOCFORGE_VERSION = "dev"


def export(
    doc: Any,
    output_path: Path,
    title: str = "",
    author: str = "DocForge",
    keywords: list[str] | None = None,
    language: str = "en",
    template: str = "",
) -> Path:
    """Write doc to output_path, inject document metadata, validate output."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    props = doc.core_properties
    if title:
        props.title = title
    props.author = author
    props.keywords = ", ".join(keywords or [])
    props.language = language
    props.comments = (
        f"Generated by DocForge {_DOCFORGE_VERSION} "
        f"on {datetime.utcnow().isoformat()} "
        f"using template '{template}'"
    )
    props.last_modified_by = f"DocForge {_DOCFORGE_VERSION}"

    doc.save(str(output_path))

    if not output_path.exists() or output_path.stat().st_size == 0:
        raise RuntimeError(f"Export produced empty or missing file: {output_path}")

    logger.info("docx_exported", path=str(output_path), size=output_path.stat().st_size)
    return output_path
